version: '3'

services:
  # client:
  #   build: .
  #   volumes:
  #     - "./client:/app"
  #   ports:
  #     - "3031:3000"
  #   depends_on:
  #     - api
  db:
    build: ./api/src/sql
    environment:
      MYSQL_DATABASE: footballdb
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: mysql
      MYSQL_PASSWORD: example
      MYSQL_HOST: db
    ports:
    #   - "HOST_PORT:CONTAINER_PORT"
      - "3306:3306"
    # to allow connection from the native OS
    expose:
      - 3306
    volumes:
      - ./docker/data/db:/var/lib/mysql

  api:
    build: .
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: footballdb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: example
      PORT: 3000
      API_TOKEN: 0c006aa5775f476bbd801d9d1443c1c3
    restart: on-failure
    volumes:
      - "./api:/app"
    ports:
      # - "HOST_PORT:CONTAINER_PORT"
      - "3000:3000"
    depends_on:
      - db
    links: 
      - db
    # to allow connection from the native OS
    expose:
      - 3000